# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config
, lib
, pkgs
, modulesPath
, host
, ...
}: {
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "thunderbolt" "nvme" "usb_storage" "sd_mod" "sr_mod" ];
  boot.blacklistedKernelModules = [ "firewire_ohci" "psmouse" ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];
  boot.kernelParams = [ "mem_sleep_default=deep" ];
  services.throttled.enable = true;

  hardware.enableRedistributableFirmware = lib.mkDefault true;
  services.thermald.enable = lib.mkDefault true;
  services.fwupd.enable = lib.mkDefault true;

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/ebaead83-efbe-44fd-a774-267c99d4f91b";
    fsType = "ext4";
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/B153-F24A";
    fsType = "vfat";
  };

  swapDevices = [ ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  # networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp0s13f0u1u4.useDHCP = lib.mkDefault true;
  networking.interfaces.enp0s31f6.useDHCP = lib.mkDefault true;
  networking.interfaces.wlp0s20f3.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  powerManagement.cpuFreqGovernor = lib.mkDefault "powersave";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;

  # networking = with host; {
  #   useDHCP = false; # Deprecated
  #   hostName = hostName;
  #   networkmanager.enable = true;
  #   interfaces = {
  #     enp0s25 = {
  #       useDHCP = true; # For versatility sake, manually edit IP on nm-applet.
  #       #ipv4.addresses = [ {
  #       #    address = "192.168.0.51";
  #       #    prefixLength = 24;
  #       #} ];
  #     };
  #     wlo1 = {
  #       useDHCP = true;
  #       #ipv4.addresses = [ {
  #       #  address = "192.168.0.51";
  #       #  prefixLength = 24;
  #       #} ];
  #     };
  #   };
  #   defaultGateway = "192.168.0.1";
  #   nameservers = [ "192.168.0.4" ];
  #   firewall = {
  #     enable = false;
  #     #allowedUDPPorts = [ 53 67 ];
  #     #allowedTCPPorts = [ 53 80 443 9443 ];
  #   };
  # };
}
