#!/usr/bin/env bash

if [[ $# -eq 1 ]]; then
	SELECTED=$1
else
	SELECTED=$(find ~/Documents/my_site/ ~/Documents/odin/ ~/Documents/ ~/.dotfiles/ -mindepth 0 -maxdepth 1 -type d | fzf)
fi

if [[ -z $SELECTED ]]; then
	exit 0
fi

SELECTED_NAME=$(basename "$SELECTED" | tr . _)
# if using i3
if pgrep -x "i3" >/dev/null; then
	WORKSPACE_NAME=$(i3-msg -t get_workspaces | jq -r '.[] | select(.focused).name')
	i3 title_format "terminal-$WORKSPACE_NAME-$SELECTED_NAME"
fi

TMUX_RUNNING=$(pgrep tmux)

echo -en "\e]2;terminal-$WORKSPACE_NAME-$SELECTED_NAME\a"

if [[ -z $TMUX ]] && [[ -z $TMUX_RUNNING ]]; then
	tmux new-session -s $SELECTED_NAME -c $SELECTED
	exit 0
fi

if ! tmux has-session -t=$SELECTED_NAME 2>/dev/null; then
	tmux new-session -ds $SELECTED_NAME -c $SELECTED
fi

if [[ -z $TMUX ]]; then
	tmux attach-session -t $SELECTED_NAME
else
	tmux switch-client -t $SELECTED_NAME
fi
